# Generated by Django 4.1.5 on 2023-01-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_courses_alter_order_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="courses",
            new_name="course",
        ),
    ]
