# Generated by Django 4.1.5 on 2023-01-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_rename_courses_order_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="material",
            field=models.CharField(max_length=100),
        ),
    ]
