# Generated by Django 4.1.5 on 2023-01-14 06:20

import django.contrib.admin.widgets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="dob",
            field=models.DateField(
                verbose_name=django.contrib.admin.widgets.AdminDateWidget
            ),
        ),
    ]
