# Generated by Django 4.1.5 on 2023-01-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_order_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
